// WebSite/site/src/lib/components/WorkflowMark.svelte
<!-- WorkflowMark -- cropped from the selected A2 rotated chat image. -->
<script lang="ts">
  let {
    size = 28
  } = $props();
</script>

<img
  class="workflow-mark"
  src="/workflow-mark.png"
  alt=""
  aria-hidden="true"
  width={size}
  height={size}
  decoding="async"
  style={`--mark-size:${size}px`}
/>

<style>
  .workflow-mark {
    display: block;
    flex-shrink: 0;
    width: var(--mark-size);
    height: var(--mark-size);
    object-fit: cover;
    border-radius: 5px;
  }
</style>

// WebSite/site-react/components/WorkflowMark.tsx
import * as React from "react";

export function WorkflowMark({ size = 28 }: { size?: number }) {
  return (
    <img
      className="workflow-mark"
      src="/workflow-mark.png"
      alt=""
      aria-hidden="true"
      width={size}
      height={size}
      decoding="async"
      style={{
        display: "block",
        flexShrink: 0,
        width: size,
        height: size,
        objectFit: "cover",
        borderRadius: 5,
      }}
    />
  );
}

export default WorkflowMark;
